name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first GitHub Actions Workflow!"
